kind: services
specs:
  yves:
    cpu_limit: 1099
    memory_limit: 1099
    network_mode: test
    scheduling_strategy: test
    desired_count: 2
    health_check_grace_period_seconds: 22
    deployment_maximum_percent: 22
    deployment_minimum_healthy_percent: 22
    autoscaling_enabled: 0
    autoscaling_min_capacity: 22
    autoscaling_max_capacity: 22
    load_balancer_type: test
    deregistration_delay: 22
    logs_expire: 22
  boffice:
    cpu_limit: 2099
    memory_limit: 2099
  glue:
    cpu_limit: 1099
    memory_limit: 1099