name: Configuration validation

on:
  - push

jobs:
  validation:
    runs-on: ubuntu-latest
    container: spryker/infra-validator:0.1-beta
    outputs:
      output_data: ${{ steps.validation.outputs }}
    steps:
      - uses: actions/checkout@v2
      - id: validation
        run: |
          echo $(python3 -m validator) >> $GITHUB_OUTPUT
          
  data_send:
    runs-on: ubuntu-latest
    needs: validation
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{ needs.validation.outputs.output_data }}
