name: Configuration validation

on:
  - push

jobs:
  validation:
    runs-on: ubuntu-latest
    container: spryker/infra-validator:0.1-beta
    steps:
      - uses: actions/checkout@v2
      - name: validation
        run: python3 -m validator
      - name: Request
        run: |
          echo ${{ steps.validation.outputs.stdout }}
          echo ${{ steps.validation.outputs.stderr }}
