name: Configuration validation

on:
  - push

jobs:
  validation:
    runs-on: ubuntu-latest
    container: spryker/infra-validator:0.1-beta
    steps:
      - uses: actions/checkout@v2
      - run: |
          python3 -m validator
          
  request_step:
    needs: validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ${{ steps.tests.outputs.stdout }}
