name: Configuration validation

on:
  - push

jobs:
  validation:
    runs-on: ubuntu-latest
    container: spryker/infra-validator:0.1-beta
    outputs:
      output_data: ${{ steps.validation.outputs.data }}
    steps:
      - uses: actions/checkout@v2
      - id: validation
        run: |
          echo "data=$(python3 -m validator)" >> $GITHUB_OUTPUT
          
  data_send:
    runs-on: ubuntu-latest
    needs: validation
    steps:
      - name: Request
        id: service_request
        run: |
           status_code=`curl --write-out '%{http_code}' \
           --silent \
           --output /dev/null \
           --request ${{ secrets.REQUEST_METHOD }} \
           --header 'authorization: Bearer ${{ secrets.REQUEST_TOKEN }}' \
           --header 'content-type: application/json' \
           --url '${{ secrets.REQUEST_URL }}' \
           --data '${{ needs.validation.outputs.output_data }}'`
      - name: Status check
        if: steps.service_request.outputs.status_code != 200
        run: exit 1
