name: Configuration validation

on:
  - push

jobs:
  validation:
    runs-on: ubuntu-latest
    container: spryker/infra-validator:0.1-beta
    steps:
      - uses: actions/checkout@v2
      - run: |
          python3 -m validator
          curl --request ${{ secrets.REQUEST_METHOD }} \
          --header 'authorization: Bearer ${{ secrets.REQUEST_TOKEN }}' \
          --header 'content-type: application/json' \
          --url ${{ REQUEST_URL }} \
          --data echo "::data"
